# Data Exploration Notebook

This notebook will guide you through the initial steps of exploring the dataset located in the `data/Working File Phase I (1).xlsx` file.

## Import Required Libraries

Let's import the libraries needed for data exploration: pandas, numpy, and matplotlib.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
## lets set pandas to display all columns
pd.set_option('display.max_columns', None)

## Load the Dataset

Load the Excel file from the `data` directory into a pandas DataFrame.

In [3]:
# Load the Excel file into a DataFrame
df = pd.read_excel('/workspaces/studious-fishstick/data/Working File Phase I (1).xlsx')
df.shape

(22120, 32)

## Display Basic Information About the Data

Let's look at the basic info and summary statistics of the dataset.

In [4]:
# Show info and summary statistics
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22120 entries, 0 to 22119
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   primary_key   21915 non-null  float64
 1   PC_2Digit     22120 non-null  int64
 2   AC_3Digit     22120 non-null  int64
 3   pc_name       22120 non-null  object
 4   ac_name       21916 non-null  object
 5   Booth_3Digit  22120 non-null  int64
 6   pc_serial     22120 non-null  int64
 7   ac_serial     22120 non-null  int64
 8   SlNo          20341 non-null  object
 9   PSNo          20341 non-null  object
 10  BOOTHNAME     22120 non-null  object
 11  BJP           22120 non-null  int64
 12  PC_BJP        22118 non-null  float64
 13  TMC           22120 non-null  int64
 14  PC_TMC        22120 non-null  float64
 15  LF            22116 non-null  float64
 16  PC_LF         22116 non-null  float64
 17  ValidVotes    22117 non-null  float64
 18  Voters2024    22120 non-null  int64
 19  BoothNo       22120 non-null  int64
 20  P_20          22120 non-null  float64
 21  P_20_30       22120 non-null  float64
 22  P_30_40       22120 non-null  float64
 23  P_40_50       22120 non-null  float64
 24  P_50_60       22120 non-null  float64
 25  Above_60      22120 non-null  float64
 26  MALE          22120 non-null  float64
 27  FEMALE        22120 non-null  float64
 28  THGEN         22120 non-null  float64
 29  AVGAGE        22120 non-null  float64
 30  Minority      22120 non-null  float64
 31  PIN           22120 non-null  int64
dtypes: float64(17), int64(10), object(5)
memory usage: 5.4+ MB

,primary_key,PC_2Digit,AC_3Digit,pc_name,ac_name,Booth_3Digit,pc_serial,ac_serial,SlNo,PSNo,BOOTHNAME,BJP,PC_BJP,TMC,PC_TMC,LF,PC_LF,ValidVotes,Voters2024,BoothNo,P_20,P_20_30,P_30_40,P_40_50,P_50_60,Above_60,MALE,FEMALE,THGEN,AVGAGE,Minority,PIN
0,11062001.0,11,62,MURSHIDABAD,Bhagawangola,1,11,62,1,1,1 - Aarijapur Malopada Primary School,85,13.10,499,76.89,51.0,7.86,649.0,759,1,7.16,24.14,24.54,11.14,16.05,16.98,55.84,44.16,0.0,42.29,0.53,742135
1,11062002.0,11,62,MURSHIDABAD,Bhagawangola,2,11,62,2,2,2 - Aarijapur Malopada Primary School,106,16.08,483,73.29,64.0,9.71,659.0,797,2,4.71,28.78,24.94,10.92,16.38,14.27,56.45,43.55,0.0,41.54,3.23,742135
2,11062003.0,11,62,MURSHIDABAD,Bhagawangola,3,11,62,3,3,3 - Lalitakudi Primary School,132,12.29,855,79.61,63.0,5.87,1074.0,1263,3,4.99,23.56,24.73,14.74,15.13,16.85,56.24,43.76,0.0,42.77,0.08,742135
3,11062004.0,11,62,MURSHIDABAD,Bhagawangola,4,11,62,4,4,4 - Odahar Primary School,221,41.86,80,15.15,209.0,39.58,528.0,741,4,5.47,30.78,26.40,13.68,11.90,11.76,56.50,43.50,0.0,39.36,78.25,742135
4,11062005.0,11,62,MURSHIDABAD,Bhagawangola,5,11,62,5,5,5 - Odahar Primary School,57,9.47,418,69.44,120.0,19.93,602.0,745,5,3.23,27.02,28.36,11.56,15.99,13.84,52.69,47.31,0.0,41.56,10.75,742135

## Preview the First Few Rows

Let's preview the first few rows of the dataset to get a sense of the data.

In [5]:
# Display the first five rows
df.head()

,primary_key,PC_2Digit,AC_3Digit,pc_name,ac_name,Booth_3Digit,pc_serial,ac_serial,SlNo,PSNo,BOOTHNAME,BJP,PC_BJP,TMC,PC_TMC,LF,PC_LF,ValidVotes,Voters2024,BoothNo,P_20,P_20_30,P_30_40,P_40_50,P_50_60,Above_60,MALE,FEMALE,THGEN,AVGAGE,Minority,PIN
0,11062001.0,11,62,MURSHIDABAD,Bhagawangola,1,11,62,1,1,1 - Aarijapur Malopada Primary School,85,13.10,499,76.89,51.0,7.86,649.0,759,1,7.16,24.14,24.54,11.14,16.05,16.98,55.84,44.16,0.0,42.29,0.53,742135
1,11062002.0,11,62,MURSHIDABAD,Bhagawangola,2,11,62,2,2,2 - Aarijapur Malopada Primary School,106,16.08,483,73.29,64.0,9.71,659.0,797,2,4.71,28.78,24.94,10.92,16.38,14.27,56.45,43.55,0.0,41.54,3.23,742135
2,11062003.0,11,62,MURSHIDABAD,Bhagawangola,3,11,62,3,3,3 - Lalitakudi Primary School,132,12.29,855,79.61,63.0,5.87,1074.0,1263,3,4.99,23.56,24.73,14.74,15.13,16.85,56.24,43.76,0.0,42.77,0.08,742135
3,11062004.0,11,62,MURSHIDABAD,Bhagawangola,4,11,62,4,4,4 - Odahar Primary School,221,41.86,80,15.15,209.0,39.58,528.0,741,4,5.47,30.78,26.40,13.68,11.90,11.76,56.50,43.50,0.0,39.36,78.25,742135
4,11062005.0,11,62,MURSHIDABAD,Bhagawangola,5,11,62,5,5,5 - Odahar Primary School,57,9.47,418,69.44,120.0,19.93,602.0,745,5,3.23,27.02,28.36,11.56,15.99,13.84,52.69,47.31,0.0,41.56,10.75,742135

In [6]:
df.columns

Index(['primary_key', 'PC_2Digit', 'AC_3Digit', 'pc_name', 'ac_name',
       'Booth_3Digit', 'pc_serial', 'ac_serial', 'SlNo', 'PSNo', 'BOOTHNAME',
       'BJP', 'PC_BJP', 'TMC', 'PC_TMC', 'LF', 'PC_LF', 'ValidVotes',
       'Voters2024', 'BoothNo', 'P_20', 'P_20_30', 'P_30_40', 'P_40_50',
       'P_50_60', 'Above_60', 'MALE', 'FEMALE', 'THGEN', 'AVGAGE', 'Minority',
       'PIN'],
      dtype='object')

In [10]:
df.ac_name.unique()

array(['Bhagawangola', 'Raninagar', 'Murshidabad', 'Hariharpara',
       'Domkal', 'Jalangi', 'Karimpur', 'Tehatta', 'Palashipara',
       'Kaliganj', 'Nakashipara', 'Chapra', 'Krishnanagar_Uttar',
       'Krishnanagar_Dakkhin', 'Chakdah', 'Ranaghat_Dakkhin',
       'Ranaghat_UttarPurba', 'Krishnaganj', 'Ranaghat_UttarPaschim',
       'Santipur', 'Nabadwip', 'Kalyani', 'Haringhata', 'Bagda',
       'Bongaon_Uttar', 'Bongaon_Dakkhin', 'Gaighata', 'Swarupnagar',
       'Baduria', 'Haroa', 'Minakhan', 'Sandeshkhali', 'Basirhat_Dakkhin',
       'Basirhat_Uttar', 'Hingalganj', 'Bidhan_nagar', 'Madhyamgram',
       'Deganga', 'Barasat', 'Rajarhat_Newtown', 'Habra', 'Ashoknagar',
       'Khardah', 'Dumdum_Uttar', 'Panihati', 'Kamarhati', 'Baranagar',
       'Dumdum', 'Rajarhat_Gopalpur', 'Barackpur', 'Noapara', 'Jagatdal',
       'Bhatpara', 'Naihati', 'Amdanga', 'Kasba', 'Behala_Purba',
       'Jagatbhallavpur', 'Domjur', 'Uttarpara', 'Sreerampur',
       'Champadani', 'Jangipara', 'Chanditala', 'Singur', 'Chandannagore',
       'Chunchura', 'Balagarh', 'Pandua', 'Saptagram', 'Dhanekhali',
       'Haripal', 'Tarakeshwar', 'Pursurah', 'Arambagh', 'Goghat',
       'Khanakul', 'Chandrakona', 'Maheshtala', 'Bijpur', nan],
      dtype=object)

In [10]:
# Let's understand the data structure better
print("Dataset shape:", df.shape)
print("\nNumber of unique Assembly Constituencies:", df['ac_name'].nunique())
print("Number of unique Parliamentary Constituencies:", df['pc_name'].nunique())
print("Total number of booths:", df['BOOTHNAME'].nunique())

# Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# Sample of Assembly Constituencies
print("\nSample Assembly Constituencies:")
print(df['ac_name'].unique()[:10])

# Vote share analysis - basic overview
print("\nBasic vote share statistics:")
print("BJP vote share - Min:", df['BJP'].min(), "Max:", df['BJP'].max(), "Mean:", df['BJP'].mean())
print("TMC vote share - Min:", df['TMC'].min(), "Max:", df['TMC'].max(), "Mean:", df['TMC'].mean()) 
print("LF vote share - Min:", df['LF'].min(), "Max:", df['LF'].max(), "Mean:", df['LF'].mean())

Dataset shape: (22120, 32)

Number of unique Assembly Constituencies: 80
Number of unique Parliamentary Constituencies: 13
Total number of booths: 21892

Missing values per column:
primary_key      205
PC_2Digit          0
AC_3Digit          0
pc_name            0
ac_name          204
Booth_3Digit       0
pc_serial          0
ac_serial          0
SlNo            1779
PSNo            1779
BOOTHNAME          0
BJP                0
PC_BJP             2
TMC                0
PC_TMC             0
LF                 4
PC_LF              4
ValidVotes         3
Voters2024         0
BoothNo            0
P_20               0
P_20_30            0
P_30_40            0
P_40_50            0
P_50_60            0
Above_60           0
MALE               0
FEMALE             0
THGEN              0
AVGAGE             0
Minority           0
PIN                0
dtype: int64

Sample Assembly Constituencies:
['Bhagawangola' 'Raninagar' 'Murshidabad' 'Hariharpara' 'Domkal' 'Jalangi'
 'Karimpur' 'Tehatta' 'Palashipara' 'Kaliganj']

Basic vote share statistics:
BJP vote share - Min: 0 Max: 1126 Mean: 250.30682640144664
TMC vote share - Min: 0 Max: 1079 Mean: 302.5836347197107
LF vote share - Min: 0.0 Max: 1007.0 Mean: 163.46575691806837

In [11]:
# Additional exploration for LF perspective analysis
print("\n" + "="*50)
print("DETAILED DATA EXPLORATION FOR LF ANALYSIS")
print("="*50)

# Check data types and sample values
print("\nData types:")
print(df.dtypes)

print("\nSample booth-level data (first 3 rows):")
print(df[['ac_name', 'BOOTHNAME', 'BJP', 'TMC', 'LF', 'ValidVotes', 'P_20', 'P_30_40', 'MALE', 'FEMALE', 'Minority']].head(3))

# LF performance overview
print(f"\nLF Performance Overview:")
print(f"Average LF vote share across all booths: {df['LF'].mean():.2f}%")
print(f"LF vote share standard deviation: {df['LF'].std():.2f}%")
print(f"Booths where LF > 30%: {len(df[df['LF'] > 30])}")
print(f"Booths where LF > 50%: {len(df[df['LF'] > 50])}")

# Assembly constituency wise LF performance
ac_lf_performance = df.groupby('ac_name')['LF'].agg(['mean', 'std', 'count']).round(2)
ac_lf_performance.columns = ['Avg_LF_Vote_Share', 'StdDev_LF_Vote_Share', 'Total_Booths']
print(f"\nTop 5 Assembly Constituencies by LF performance:")
print(ac_lf_performance.sort_values('Avg_LF_Vote_Share', ascending=False).head())

print(f"\nBottom 5 Assembly Constituencies by LF performance:")
print(ac_lf_performance.sort_values('Avg_LF_Vote_Share', ascending=True).head())

# Check age group columns to understand demographics
age_cols = ['P_20', 'P_20_30', 'P_30_40', 'P_40_50', 'P_50_60', 'Above_60']
print(f"\nAge group data sample:")
print(df[age_cols].head())
print(f"\nAge group data statistics:")
print(df[age_cols].describe())

==================================================
DETAILED DATA EXPLORATION FOR LF ANALYSIS
==================================================

Data types:
primary_key     float64
PC_2Digit         int64
AC_3Digit         int64
pc_name          object
ac_name          object
Booth_3Digit      int64
pc_serial         int64
ac_serial         int64
SlNo             object
PSNo             object
BOOTHNAME        object
BJP               int64
PC_BJP          float64
TMC               int64
PC_TMC          float64
LF              float64
PC_LF           float64
ValidVotes      float64
Voters2024        int64
BoothNo           int64
P_20            float64
P_20_30         float64
P_30_40         float64
P_40_50         float64
P_50_60         float64
Above_60        float64
MALE            float64
FEMALE          float64
THGEN           float64
AVGAGE          float64
Minority        float64
PIN               int64
dtype: object

Sample booth-level data (first 3 rows):
        ac_name                              BOOTHNAME  BJP  TMC    LF  \
0  Bhagawangola  1 - Aarijapur Malopada Primary School   85  499  51.0
1  Bhagawangola  2 - Aarijapur Malopada Primary School  106  483  64.0
2  Bhagawangola          3 - Lalitakudi Primary School  132  855  63.0

   ValidVotes  P_20  P_30_40   MALE  FEMALE  Minority
0       649.0  7.16    24.54  55.84   44.16      0.53
1       659.0  4.71    24.94  56.45   43.55      3.23
2      1074.0  4.99    24.73  56.24   43.76      0.08

LF Performance Overview:
Average LF vote share across all booths: 163.47%
LF vote share standard deviation: 153.58%
Booths where LF > 30%: 17837
Booths where LF > 50%: 15522

Top 5 Assembly Constituencies by LF performance:
                 Avg_LF_Vote_Share  StdDev_LF_Vote_Share  Total_Booths
ac_name
Bijpur                      423.00                   NaN             1
Gaighata                    420.41                132.56           274
Bongaon_Dakkhin             401.69                139.38           270
Bongaon_Uttar               399.45                149.03           275
Haringhata                  383.42                176.93           257

Bottom 5 Assembly Constituencies by LF performance:
              Avg_LF_Vote_Share  StdDev_LF_Vote_Share  Total_Booths
ac_name
Sandeshkhali              15.26                 16.70           250
Minakhan                  22.80                 21.79           244
Haroa                     26.98                 28.87           276
Bhatpara                  28.17                 38.36           163
Hingalganj                28.31                 33.85           254

Age group data sample:
   P_20  P_20_30  P_30_40  P_40_50  P_50_60  Above_60
0  7.16    24.14    24.54    11.14    16.05     16.98
1  4.71    28.78    24.94    10.92    16.38     14.27
2  4.99    23.56    24.73    14.74    15.13     16.85
3  5.47    30.78    26.40    13.68    11.90     11.76
4  3.23    27.02    28.36    11.56    15.99     13.84

Age group data statistics:
               P_20       P_20_30       P_30_40       P_40_50       P_50_60  \
count  22120.000000  22120.000000  22120.000000  22120.000000  22120.000000
mean       3.320437     19.536557     26.641332     17.641682     16.576209
std        1.254916      5.265137      4.044292      3.027737      2.755126
min        0.000000      5.190000      9.940000      5.940000      2.690000
25%        2.410000     15.600000     23.870000     15.580000     14.610000
50%        3.250000     19.510000     26.720000     17.880000     16.610000
75%        4.110000     23.150000     29.350000     19.800000     18.530000
max       10.560000     38.670000     61.960000     34.710000     40.500000

           Above_60
count  22120.000000
mean      16.283802
std        5.046191
min        0.620000
25%       12.800000
50%       15.200000
75%       18.430000
max       44.720000

In [12]:
# Quick summary for planning document
print("\n" + "="*60)
print("PROJECT SCOPE SUMMARY")
print("="*60)

# Count of constituencies and booths
unique_acs = df['ac_name'].nunique()
unique_pcs = df['pc_name'].nunique()
total_booths = len(df)

print(f"Total Assembly Constituencies to analyze: {unique_acs}")
print(f"Total Parliamentary Constituencies: {unique_pcs}")
print(f"Total booths in dataset: {total_booths}")
print(f"Average booths per AC: {total_booths/unique_acs:.1f}")

# LF performance overview for context
lf_mean = df['LF'].mean()
lf_std = df['LF'].std()
lf_winning_booths = len(df[df['LF'] >= df[['BJP', 'TMC', 'LF']].max(axis=1)])

print(f"\nLF Current Performance:")
print(f"Average LF vote share: {lf_mean:.2f}%")
print(f"Standard deviation: {lf_std:.2f}%")
print(f"Booths where LF is leading: {lf_winning_booths} ({lf_winning_booths/total_booths*100:.1f}%)")

# Opportunity analysis
close_second = len(df[(df['LF'] < df[['BJP', 'TMC', 'LF']].max(axis=1)) & 
                     (df[['BJP', 'TMC', 'LF']].max(axis=1) - df['LF'] <= 15)])

print(f"Booths where LF is within 15% of leader: {close_second} ({close_second/total_booths*100:.1f}%)")

print(f"\nEstimated reports to generate: {unique_acs} detailed AC reports")
print("="*60)

============================================================
PROJECT SCOPE SUMMARY
============================================================
Total Assembly Constituencies to analyze: 80
Total Parliamentary Constituencies: 13
Total booths in dataset: 22120
Average booths per AC: 276.5

LF Current Performance:
Average LF vote share: 163.47%
Standard deviation: 153.58%
Booths where LF is leading: 3438 (15.5%)
Booths where LF is within 15% of leader: 317 (1.4%)

Estimated reports to generate: 80 detailed AC reports
============================================================

In [13]:
# Investigate the unusual LF vote share values
print("\n" + "="*50)
print("DATA QUALITY CHECK")
print("="*50)

print("LF vote share statistics:")
print(f"Min: {df['LF'].min()}")
print(f"Max: {df['LF'].max()}")
print(f"Mean: {df['LF'].mean():.2f}")
print(f"Median: {df['LF'].median():.2f}")

print("\nSample of high LF values:")
print(df[df['LF'] > 100][['ac_name', 'BOOTHNAME', 'LF', 'BJP', 'TMC']].head())

print("\nChecking all party vote shares:")
print(f"BJP - Min: {df['BJP'].min():.2f}, Max: {df['BJP'].max():.2f}, Mean: {df['BJP'].mean():.2f}")
print(f"TMC - Min: {df['TMC'].min():.2f}, Max: {df['TMC'].max():.2f}, Mean: {df['TMC'].mean():.2f}")
print(f"LF  - Min: {df['LF'].min():.2f}, Max: {df['LF'].max():.2f}, Mean: {df['LF'].mean():.2f}")

# Check if these might be vote counts instead of percentages
print("\nChecking ValidVotes vs party vote values:")
sample_booths = df.sample(5)
for idx, row in sample_booths.iterrows():
    total_party_votes = row['BJP'] + row['TMC'] + row['LF'] 
    print(f"Booth: {row['BOOTHNAME'][:20]}... | ValidVotes: {row['ValidVotes']} | BJP+TMC+LF: {total_party_votes:.1f}")

print("\nCorrecting interpretation if needed...")
# If the values are actually vote counts, convert to percentages
if df['LF'].mean() > 50:  # Likely vote counts, not percentages
    print("Values appear to be vote counts, converting to percentages...")
    df['BJP_pct'] = (df['BJP'] / df['ValidVotes']) * 100
    df['TMC_pct'] = (df['TMC'] / df['ValidVotes']) * 100  
    df['LF_pct'] = (df['LF'] / df['ValidVotes']) * 100
    
    print(f"\nCorrected LF performance:")
    print(f"Average LF vote share: {df['LF_pct'].mean():.2f}%")
    print(f"LF vote share standard deviation: {df['LF_pct'].std():.2f}%")
    lf_winning_booths_corrected = len(df[df['LF_pct'] >= df[['BJP_pct', 'TMC_pct', 'LF_pct']].max(axis=1)])
    print(f"Booths where LF is leading: {lf_winning_booths_corrected} ({lf_winning_booths_corrected/len(df)*100:.1f}%)")
else:
    print("Values appear to be percentages already")
    df['BJP_pct'] = df['BJP']
    df['TMC_pct'] = df['TMC']
    df['LF_pct'] = df['LF']

==================================================
DATA QUALITY CHECK
==================================================
LF vote share statistics:
Min: 0.0
Max: 1007.0
Mean: 163.47
Median: 110.00

Sample of high LF values:
        ac_name                   BOOTHNAME     LF  BJP  TMC
3  Bhagawangola   4 - Odahar Primary School  209.0  221   80
4  Bhagawangola   5 - Odahar Primary School  120.0   57  418
5  Bhagawangola       6 - Odahar Hai School  405.0  277  141
6  Bhagawangola       7 - Odahar Hai School  367.0  364   12
7  Bhagawangola  8 - Dostina Primary School  397.0  347   13

Checking all party vote shares:
BJP - Min: 0.00, Max: 1126.00, Mean: 250.31
TMC - Min: 0.00, Max: 1079.00, Mean: 302.58
LF  - Min: 0.00, Max: 1007.00, Mean: 163.47

Checking ValidVotes vs party vote values:
Booth: 296 - Monber Kalital... | ValidVotes: 456.0 | BJP+TMC+LF: 450.0
Booth: 199 - Kaniara S.K.U.... | ValidVotes: 899.0 | BJP+TMC+LF: 872.0
Booth: 73 - Shakdaha High S... | ValidVotes: 822.0 | BJP+TMC+LF: 818.0
Booth: 254 - Kanksa Rahimia... | ValidVotes: 700.0 | BJP+TMC+LF: 692.0
Booth: 109 - Maharani Jyoti... | ValidVotes: 832.0 | BJP+TMC+LF: 822.0

Correcting interpretation if needed...
Values appear to be vote counts, converting to percentages...

Corrected LF performance:
Average LF vote share: 21.87%
LF vote share standard deviation: 18.90%
Booths where LF is leading: 3436 (15.5%)